version: '3'

services:

  postgresdb:
    image: postgres:9.6
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
    volumes:
      - data:/var/lib/postgresql/data

  nodejs-app:
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: nodejs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - ./app/:/app/
      - /app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  data:
  pgadmin-data: